site_name: Fabric Copilot Lab
repo_url: https://github.com/GiullianJT/copilot-in-fabric
theme:
  name: material
  logo: assets/img/journeyteam_logo.png   # optional
nav:
  - Home: index.md            # will live in docs/index.md
  - Sessions:
      - Session 1: sessions/session1.md
      - Session 2: sessions/session2.md
      - Session 3: sessions/session3.md
plugins:
  - search
  - glightbox
#   - pdf-export        # exports every page to /pdf/

